### ISSUE TITLE
Can't resolve 'react-loading-skeleton'

### ISSUE THREAD

**Issue by jswift** [GeekEast/restaurant#2]
After running `yarn install && yarn start`, I get the following error

```
./src/components/Item.tsx
Module not found: Can't resolve 'react-loading-skeleton' in '/code-challenges/james-tan-zomato/src/components'
```

Versions:
- node v10.17.0
- yarn 1.22.10

**Comment by GeekEast** [comment]
Hi @jswift , thanks for your feedback. I have removed the `react-loading-skeleton` in `Item.tsx` in all branches. Please `git pull` and then `yarn start`.
